version: "3.1"
services:
  nginx-rproxy:
    container_name: nginx-rproxy
    image: cc164/hw-charging:nginx
    ports:
      - 8285:8285
    restart: always
    volumes:
      - "./nginx-rproxy.conf:/etc/nginx/conf.d/default.conf"
    #Set resource limits
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
    #Set max log size
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  hwcharging-node:
    container_name: hw-charging-node
    image: cc164/hw-charging:node
    ports:
      - 8286:8286
    restart: always
    environment:
      - HOST_PORT=8286
      - HOST_NAME=https://www.macs.hw.ac.uk/hwcharging
      - MODE=PROD
    secrets:
      - db-url
      - jwt-secret
      - email-password
    #Set resource limits
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
    #Set max log size
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  hwcharging-react:
    container_name: hw-charging-react
    image: cc164/hw-charging:react
    ports:
      - 8287:8287
    restart: always
    environment:
      - PORT=8287
    #Set resource limits
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
    #Set max log size
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

secrets:
  db-url:
    external: true
  jwt-secret:
    external: true
  email-password:
    external: true
