version: "3.8"
services:
  nginx-rproxy:
    container_name: nginx-rproxy
    image: nginx:latest
    ports: 
      - 8285:8285
    restart: always
    volumes:
      - "./nginx-rproxy.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - hwcharging-node
      - hwcharging-react
  
  hwcharging-node:
    container_name: hwcharging-node
    image: node-test
    ports:
      - 8286:8286
    restart: always
    environment:
      - HOST_PORT=8286
      - HOST_NAME=http://127.0.0.1:8285/hwcharging
      - MODE=TEST
      - DATABASE_URL=mysql://hwcharging:password@hwcharging-db:3306/hwcharging
      - JWT_SECRET=TESTSECRETDONOTUSEINPRODUCTION
    depends_on:
      - hwcharging-db

  hwcharging-react:
    container_name: hwcharging-react
    image: react-test
    ports:
      - 8287:8287
    restart: always
    environment:
      - PORT=8287

  hwcharging-db:
    container_name: hwcharging-db
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=hwcharging
      - MYSQL_USER=hwcharging
      - MYSQL_PASSWORD=password
    volumes:
      - "./hwcharging.sql:/docker-entrypoint-initdb.d/init.sql"

  hwcharging-test:
    container_name: hwcharging-test
    image: node-unit-test
    ports:
      - 3003:3003
    restart: always
    environment:
      - HOST_PORT=3003
      - DB_HOST=hwcharging-db
      - DB_USER=hwcharging
      - DB_PASSWORD=password
      - DB_NAME=hwcharging
      - TEST_ENDPOINT=http://nginx-rproxy:8285/hwcharging
      - JWT_SECRET=TESTSECRETDONOTUSEINPRODUCTION
    volumes:
      - "./hwcharging.sql:/init-db.sql"
    depends_on:
      - hwcharging-node
      - hwcharging-react
      - nginx-rproxy